import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1.0
};

export const metadata: Metadata = {
  title: "Менеджер Задач 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* <nav className="navigation-panel --mobile-only">
          <div className="navigation-panel__left">
            <span className="app-logo">Менеджер Задач 2.0</span>
          </div>
          <div className="navigation-panel__right"></div>
        </nav> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
